version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montink_erp_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - montink_network

  db:
    image: mysql:8.0
    container_name: montink_erp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: montink_erp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: montink
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - montink_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: montink_erp_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - montink_network

networks:
  montink_network:
    driver: bridge 