version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_erp_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mini_erp_network

  nginx:
    image: nginx:alpine
    container_name: mini_erp_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
      - mini_erp_network

  db:
    image: mysql:8.0
    container_name: mini_erp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mini_erp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: erp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - mini_erp_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mini_erp_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mini_erp_network

networks:
  mini_erp_network:
    driver: bridge
